sync-github-prs:
  tags: [nobatch]
  only:
    - schedules
  variables:
    GIT_STRATEGY: clone
  script:
    - module load python/3.7.0
    - pip3 install --user PyGithub
    - module load git
    - bash scripts/ci/gitlab-ci/pr-sync.sh

.all-steps:
  except:
    - schedules
  variables:
    GITLAB_SITE: "OLCF GitLab"
    CMAKE_ENV_MODULE: "cmake"
  script:
    - bash scripts/ci/gitlab-ci/run.sh update
    - bash scripts/ci/gitlab-ci/run.sh configure
    - bash scripts/ci/gitlab-ci/run.sh build
    - bash scripts/ci/gitlab-ci/run.sh test

ascent-xl:
  extends:
  - .all-steps
  tags: [nobatch]

ascent-gcc:
  extends:
  - .all-steps
  tags: [nobatch]

#ascent-xl-smpi:
#  extends:
#  - .all-steps
#  tags: [batch]
#  variables:
#    SCHEDULER_PARAMETERS: "-P CSC303 -W 1:00 -nnodes 1"
